### ISSUE TITLE
Conditions using number crash app

### ISSUE THREAD

**Issue by stevenolen** [ohmage/android-lib#88] opened 2013-08-15 21:20 UTC
condition using the number result from a previous question, ie: (question2 == 3) crashes app with this log:

```
E/AndroidRuntime( 2380): FATAL EXCEPTION: main
E/AndroidRuntime( 2380): java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Integer
E/AndroidRuntime( 2380):    at org.ohmage.conditionevaluator.comparator.NumberDataPointComparator.equals(NumberDataPointComparator.java:30)
E/AndroidRuntime( 2380):    at org.ohmage.conditionevaluator.comparator.BasicDataPointComparator.compare(BasicDataPointComparator.java:59)
E/AndroidRuntime( 2380):    at org.ohmage.conditionevaluator.ConditionDepthFirst.visit(ConditionDepthFirst.java:277)
E/AndroidRuntime( 2380):    at org.andwellness.config.grammar.syntaxtree.expr.accept(expr.java:28)
E/AndroidRuntime( 2380):    at org.ohmage.conditionevaluator.ConditionDepthFirst.visit(ConditionDepthFirst.java:123)
E/AndroidRuntime( 2380):    at org.andwellness.config.grammar.syntaxtree.sentence.accept(sentence.java:23)
E/AndroidRuntime( 2380):    at org.ohmage.conditionevaluator.ConditionDepthFirst.visit(ConditionDepthFirst.java:133)
E/AndroidRuntime( 2380):    at org.andwellness.config.grammar.syntaxtree.sentence.accept(sentence.java:23)
E/AndroidRuntime( 2380):    at org.ohmage.conditionevaluator.ConditionDepthFirst.visit(ConditionDepthFirst.java:90)
E/AndroidRuntime( 2380):    at org.ohmage.conditionevaluator.DataPointConditionEvaluator.evaluateCondition(DataPointConditionEvaluator.java:73)
E/AndroidRuntime( 2380):    at org.ohmage.activity.SurveyActivity$2.onClick(SurveyActivity.java:395)
E/AndroidRuntime( 2380):    at android.view.View.performClick(View.java:4240)
E/AndroidRuntime( 2380):    at android.view.View$PerformClick.run(View.java:17721)
E/AndroidRuntime( 2380):    at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime( 2380):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 2380):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2380):    at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 2380):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2380):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 2380):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 2380):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2380):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  539):   Force finishing activity org.ohmage.app/org.ohmage.activity.SurveyActivity
W/ActivityManager(  539): Activity pause timeout for ActivityRecord{42315628 u0 org.ohmage.app/org.ohmage.activity.SurveyActivity}
```

**Comment by cketcham** [comment] 2013-08-15 21:36
this is a duplicate of #82 and has been fixed but not put on the play store.

**Closed as completed** 2013-08-15 21:37 UTC
Labels: bug

**Comment by stevenolen** [comment] 2013-08-15 21:43
sorry I missed that! :)

**Comment by cketcham** [comment] 2013-08-15 21:47
no problem. I should have made a new apk for the store a while ago...
