### ISSUE TITLE
Reminder did not trigger after restarting 4.0 android emulator

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#29] opened 2013-04-01 22:57 UTC
I added a time reminder on android 4.0 emulator (target: Google API) then restarted the device. On the set time no notification shows and the survey with the reminder didn't show in the pending survey.

**Comment by cketcham** [comment] 2013-04-02 18:08
I wonder if this bug is limited to the emulator? or it could be that the trigger already when off? (If you set a trigger and it goes off once, you have to delete it and set another trigger. If you just change the time of an existing trigger, it wont go off until the next day). I tried setting a notification on my phone, restarted the phone, and the notification went off at the correct time.

Do you have steps to reproduce this bug?

**Comment by ctrance** [comment] 2013-04-03 16:46
1. Started the emulator, set up with target=Google API & platform=4.0.
2. Installed the apk from web.ohmage.org/~cketcham/ohmageApp-release.apk
3. Added a campaign.
4. Set up a time reminder for the added campaign.
5. Closed the emulator.
6. Relaunched the emulator, w/o wiping user data.
   >>The reminder didn't go off at the set time<<

**Comment by cketcham** [comment] 2013-04-03 22:55
tested on a device and did not have a problem for reminders which were set after the phone was turned back on. Any reminders which were set while the phone was off were not shown. created #34 to deal with this bug.

Closing this since it is limited to emulators

**Closed as completed by cketcham** 2013-04-03 22:55 UTC
