### ISSUE TITLE
Mobility crashes on android 2.2

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#26] opened 2013-04-01 21:53 UTC
When I open 'Mobility' app on the 2.2 android emulator (Target: Google API), I'm getting error 'Application Mobility (in process org.ohmage.mobility is not responding'. Then on ohmage-dev, when I go to Mobility>Control and selected a sampling interval I'm always kicked back to the main dashboard.

Is the app required to be compatible with android 2.2? If no, then please close this issue.

**Comment by cketcham** [comment] 2013-04-02 16:08
Can you include the log from adb for this crash?

**Comment by ctrance** [comment] 2013-04-03 17:13
This is the log when launching Mobility app on the android 2.2 emulator 
04-03 17:06:27.229: W/ActivityManager(71): Timeout of broadcast BroadcastRecord{4514bc88 org.ohmage.mobility.record} - receiver=android.os.BinderProxy@4504d9b8
04-03 17:06:27.229: W/ActivityManager(71): Receiver during timeout: ResolveInfo{4514bb78 org.ohmage.mobility.SampleReceiver p=0 o=0 m=0x108000}
04-03 17:06:27.495: E/ActivityManager(71): ANR in org.ohmage.mobility
04-03 17:06:27.495: E/ActivityManager(71): Reason: Broadcast of Intent { act=org.ohmage.mobility.record flg=0x4 cmp=org.ohmage.mobility/.SampleReceiver (has extras) }
04-03 17:06:27.495: E/ActivityManager(71): Load: 1.27 / 0.96 / 0.66
04-03 17:06:27.495: E/ActivityManager(71): CPU usage from 11579ms to 19ms ago:
04-03 17:06:27.495: E/ActivityManager(71):   system_server: 19% = 15% user + 3% kernel / faults: 924 minor
04-03 17:06:27.495: E/ActivityManager(71):   ndroid.launcher: 8% = 5% user + 2% kernel / faults: 3622 minor
04-03 17:06:27.495: E/ActivityManager(71):   org.ohmage.dev: 6% = 3% user + 2% kernel / faults: 3937 minor
04-03 17:06:27.495: E/ActivityManager(71):   qemud: 6% = 0% user + 5% kernel
04-03 17:06:27.495: E/ActivityManager(71):   oid.development: 1% = 0% user + 0% kernel / faults: 7 minor
04-03 17:06:27.495: E/ActivityManager(71):   adbd: 0% = 0% user + 0% kernel
04-03 17:06:27.495: E/ActivityManager(71):   ndroid.settings: 0% = 0% user + 0% kernel / faults: 21 minor
04-03 17:06:27.495: E/ActivityManager(71):   putmethod.latin: 0% = 0% user + 0% kernel / faults: 10 minor
04-03 17:06:27.495: E/ActivityManager(71):   m.android.phone: 0% = 0% user + 0% kernel / faults: 18 minor
04-03 17:06:27.495: E/ActivityManager(71):   e.process.gapps: 0% = 0% user + 0% kernel / faults: 17 minor
04-03 17:06:27.495: E/ActivityManager(71):   com.android.mms: 0% = 0% user + 0% kernel / faults: 8 minor
04-03 17:06:27.495: E/ActivityManager(71):   android.browser: 0% = 0% user + 0% kernel / faults: 22 minor
04-03 17:06:27.495: E/ActivityManager(71):   .quicksearchbox: 0% = 0% user + 0% kernel / faults: 20 minor
04-03 17:06:27.495: E/ActivityManager(71):   ackageinstaller: 0% = 0% user + 0% kernel / faults: 9 minor
04-03 17:06:27.495: E/ActivityManager(71):   com.svox.pico: 0% = 0% user + 0% kernel / faults: 56 minor
04-03 17:06:27.495: E/ActivityManager(71):   logcat: 0% = 0% user + 0% kernel
04-03 17:06:27.495: E/ActivityManager(71):  +ohmage.mobility: 0% = 0% user + 0% kernel
04-03 17:06:27.495: E/ActivityManager(71):  +ohmage.mobility: 0% = 0% user + 0% kernel
04-03 17:06:27.495: E/ActivityManager(71): TOTAL: 42% = 28% user + 14% kernel
04-03 17:06:27.555: W/ActivityManager(71): Canceling start item Intent { cmp=org.ohmage.mobility/.GarbageCollectService } in service ComponentInfo{org.ohmage.mobility/org.ohmage.mobility.GarbageCollectService}
04-03 17:06:27.555: W/ActivityManager(71): Scheduling restart of crashed service org.ohmage.mobility/.GarbageCollectService in 20984ms
04-03 17:06:29.386: W/ActivityManager(71): Unable to start service Intent { act=edu.ucla.cens.systemsens.IPowerMonitor }: not found
04-03 17:06:29.466: E/WifiService(71): Failed to load Wi-Fi driver.
04-03 17:06:29.526: W/ActivityManager(71): Unable to start service Intent { act=edu.ucla.cens.systemsens.IPowerMonitor }: not found
04-03 17:06:38.092: W/ActivityManager(71): Launch timeout has expired, giving up wake lock!
04-03 17:06:38.092: W/ActivityManager(71): Activity idle timeout for HistoryRecord{450ee5a0 org.ohmage.mobility/.MobilityControl}
04-03 17:06:39.125: W/ActivityManager(71): Timeout of broadcast BroadcastRecord{452231e0 org.ohmage.mobility.record} - receiver=android.os.BinderProxy@45274098
04-03 17:06:39.126: W/ActivityManager(71): Receiver during timeout: ResolveInfo{45057e88 org.ohmage.mobility.SampleReceiver p=0 o=0 m=0x108000}

**Comment by ctrance** [comment] 2013-04-03 17:20
This is the log when opening 'Control' from Mobility module in ohmage-dev app.

04-03 17:14:17.696: E/MapActivity(854): Couldn't get connection factory client
04-03 17:14:22.668: W/ActivityManager(71): Timeout of broadcast BroadcastRecord{45137840 org.ohmage.mobility.garbagecollect} - receiver=android.os.BinderProxy@450d05e0
04-03 17:14:22.668: W/ActivityManager(71): Receiver during timeout: ResolveInfo{45137730 org.ohmage.mobility.GarbageCollectReceiver p=0 o=0 m=0x108000}
04-03 17:14:22.956: E/ActivityManager(71): ANR in org.ohmage.mobility
04-03 17:14:22.956: E/ActivityManager(71): Reason: Broadcast of Intent { act=org.ohmage.mobility.garbagecollect flg=0x4 cmp=org.ohmage.mobility/.GarbageCollectReceiver (has extras) }
04-03 17:14:22.956: E/ActivityManager(71): Load: 0.61 / 0.63 / 0.6
04-03 17:14:22.956: E/ActivityManager(71): CPU usage from 11350ms to 19ms ago:
04-03 17:14:22.956: E/ActivityManager(71):   system_server: 15% = 12% user + 2% kernel / faults: 606 minor
04-03 17:14:22.956: E/ActivityManager(71):   org.ohmage.dev: 8% = 6% user + 1% kernel / faults: 1867 minor
04-03 17:14:22.956: E/ActivityManager(71):   qemud: 6% = 1% user + 4% kernel
04-03 17:14:22.956: E/ActivityManager(71):   ndroid.launcher: 1% = 1% user + 0% kernel / faults: 11 minor
04-03 17:14:22.956: E/ActivityManager(71):   logcat: 0% = 0% user + 0% kernel
04-03 17:14:22.956: E/ActivityManager(71):   adbd: 0% = 0% user + 0% kernel
04-03 17:14:22.956: E/ActivityManager(71):   m.android.phone: 0% = 0% user + 0% kernel / faults: 18 minor
04-03 17:14:22.956: E/ActivityManager(71):   android.browser: 0% = 0% user + 0% kernel / faults: 22 minor
04-03 17:14:22.956: E/ActivityManager(71):   putmethod.latin: 0% = 0% user + 0% kernel / faults: 10 minor
04-03 17:14:22.956: E/ActivityManager(71):   d.process.acore: 0% = 0% user + 0% kernel / faults: 22 minor
04-03 17:14:22.956: E/ActivityManager(71):   roid.alarmclock: 0% = 0% user + 0% kernel / faults: 7 minor
04-03 17:14:22.956: E/ActivityManager(71):   e.process.gapps: 0% = 0% user + 0% kernel / faults: 20 minor
04-03 17:14:22.956: E/ActivityManager(71):   m.android.email: 0% = 0% user + 0% kernel / faults: 16 minor
04-03 17:14:22.956: E/ActivityManager(71):   .quicksearchbox: 0% = 0% user + 0% kernel / faults: 10 minor
04-03 17:14:22.956: E/ActivityManager(71):   android.protips: 0% = 0% user + 0% kernel / faults: 35 minor
04-03 17:14:22.956: E/ActivityManager(71):   ackageinstaller: 0% = 0% user + 0% kernel / faults: 9 minor
04-03 17:14:22.956: E/ActivityManager(71):   id.defcontainer: 0% = 0% user + 0% kernel / faults: 9 minor
04-03 17:14:22.956: E/ActivityManager(71):  +ohmage.mobility: 0% = 0% user + 0% kernel
04-03 17:14:22.956: E/ActivityManager(71):  +ohmage.mobility: 0% = 0% user + 0% kernel
04-03 17:14:22.956: E/ActivityManager(71): TOTAL: 39% = 26% user + 12% kernel + 0% softirq
04-03 17:14:23.016: W/ActivityManager(71): Canceling start item Intent { cmp=org.ohmage.mobility/.ClassifierService } in service ComponentInfo{org.ohmage.mobility/org.ohmage.mobility.ClassifierService}
04-03 17:14:23.016: W/ActivityManager(71): Scheduling restart of crashed service org.ohmage.mobility/.ClassifierService in 20816ms
04-03 17:14:24.096: W/ActivityManager(71): Unable to start service Intent { act=edu.ucla.cens.systemsens.IPowerMonitor }: not found
04-03 17:14:24.196: E/WifiService(71): Failed to load Wi-Fi driver.
04-03 17:14:24.276: W/ActivityManager(71): Unable to start service Intent { act=edu.ucla.cens.systemsens.IPowerMonitor }: not found
04-03 17:14:25.326: W/MapActivity(854): Recycling dispatcher com.google.googlenav.datarequest.DataRequestDispatcher@44ec0400
04-03 17:14:25.726: E/MapActivity(854): Couldn't get connection factory client
04-03 17:14:33.988: W/ActivityManager(71): Timeout of broadcast BroadcastRecord{45277a90 org.ohmage.mobility.garbagecollect} - receiver=android.os.BinderProxy@4521c678
04-03 17:14:33.988: W/ActivityManager(71): Receiver during timeout: ResolveInfo{4519af68 org.ohmage.mobility.GarbageCollectReceiver p=0 o=0 m=0x108000}
04-03 17:14:34.386: E/ActivityManager(71): ANR in org.ohmage.mobility

**Comment by cketcham** [comment] 2013-04-03 17:30
moved to https://github.com/cens/MobilityPhone/issues/23

**Comment by cketcham** [comment] 2013-04-03 17:35
actually a wifigpslocation bug. moved here https://github.com/ohmage/WiFiGPSLocation/issues/2

**Comment by cketcham** [comment] 2013-04-03 18:03
I am actually unable to reproduce this bug. can you provide the steps to reproduce? also can you make sure you are using the latest ohmage android apk?

**Comment by ctrance** [comment] 2013-04-03 18:14
I download the latest ohmage-dev apk from web.ohmage.org/~cketcham/ohmageApp-release.apk then the latest mobility 1.4.4 from web.ohmage.org/ohmage/apsk.php. To reproduce this bug, please follow the steps below:
1. installed ohmage dev first then installed mobility
2. tapped 'mobility' then go to 'controls'. selected a sampling interval '1 min'
   >>I was redirected back to the home page <<

Then I got out of ohmage-dev and opened 'mobility' app but getting error msg 'application mobility is not responding'.

**Comment by cketcham** [comment] 2013-04-03 23:10
This is actually a mobility bug and has been fixed on the play store (version 1.4.5), but was not pushed to web.ohmage.org/ohmage/apsk.php

here is the version of mobility you should test with: http://web.ohmage.org/ohmage/sw/mobility-1.4.5.apk

**Closed as completed by cketcham** 2013-04-03 23:10 UTC

**Comment by cketcham** [comment] 2013-04-03 23:12
For our reference in the future, the crash occurred because LogProbe tried to write a log before the application initialized it. This can occur in the ContentProvider because it can be created before the application.

D/MobilityContentProvider(  365): Query: content://org.ohmage.mobility.MobilityContentProvider/mobility/aggregates
D/MobilityContentProvider(  365): Query: content://org.ohmage.mobility.MobilityContentProvider/mobility/aggregates
E/DatabaseUtils(  365): Writing exception to parcel
E/DatabaseUtils(  365): java.lang.NullPointerException
E/DatabaseUtils(  365):     at java.lang.Enum.compareTo(Enum.java:135)
E/DatabaseUtils(  365):     at org.ohmage.logprobe.Log.shouldLogMessage(Log.java:23)
E/DatabaseUtils(  365):     at org.ohmage.logprobe.Log.log(Log.java:30)
E/DatabaseUtils(  365):     at org.ohmage.logprobe.Log.v(Log.java:55)
E/DatabaseUtils(  365):     at org.ohmage.mobility.MobilityContentProvider.query(MobilityContentProvider.java:233)
E/DatabaseUtils(  365):     at android.content.ContentProvider$Transport.bulkQuery(ContentProvider.java:150)
E/DatabaseUtils(  365):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:111)
E/DatabaseUtils(  365):     at android.os.Binder.execTransact(Binder.java:288)
E/DatabaseUtils(  365):     at dalvik.system.NativeStart.run(Native Method)
W/dalvikvm(  340): threadid=12: thread exiting with uncaught exception (group=0x4001d800)
E/AndroidRuntime(  340): FATAL EXCEPTION: ModernAsyncTask #3
E/AndroidRuntime(  340): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(  340):    at android.support.v4.content.ModernAsyncTask$3.done(Unknown Source)
E/AndroidRuntime(  340):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime(  340):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime(  340):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime(  340):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime(  340):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
E/AndroidRuntime(  340):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
E/AndroidRuntime(  340):    at java.lang.Thread.run(Thread.java:1096)
E/AndroidRuntime(  340): Caused by: java.lang.NullPointerException
E/AndroidRuntime(  340):    at android.os.Parcel.readException(Parcel.java:1253)
E/AndroidRuntime(  340):    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:160)
E/AndroidRuntime(  340):    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:114)
E/AndroidRuntime(  340):    at android.content.ContentProviderProxy.bulkQueryInternal(ContentProviderNative.java:330)
E/AndroidRuntime(  340):    at android.content.ContentProviderProxy.query(ContentProviderNative.java:366)
E/AndroidRuntime(  340):    at android.content.ContentResolver.query(ContentResolver.java:245)
E/AndroidRuntime(  340):    at android.support.v4.content.CursorLoader.loadInBackground(Unknown Source)
E/AndroidRuntime(  340):    at org.ohmage.loader.MobilityAggregateLoader.loadInBackground(MobilityAggregateLoader.java:34)
E/AndroidRuntime(  340):    at org.ohmage.loader.MobilityAggregateLoader.loadInBackground(MobilityAggregateLoader.java:10)
E/AndroidRuntime(  340):    at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(Unknown Source)
E/AndroidRuntime(  340):    at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source)
E/AndroidRuntime(  340):    at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source)
E/AndroidRuntime(  340):    at android.support.v4.content.ModernAsyncTask$2.call(Unknown Source)
E/AndroidRuntime(  340):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime(  340):    ... 4 more

**Comment by ctrance** [comment] 2013-04-04 15:56
The mobility 1.4.5 app is working now. However, I'll close this issue once ohmage-dev apk has been updated. Tapping 'mobility' from ohmage-dev and selecting a sampling interval still kicks me back to the dashboard.
