### ISSUE TITLE
Reminder that went off while phone was off doesn't show on Notification list

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#44] opened 2013-04-09 16:44 UTC
I set the time reminder at 10:33 am then turned off the phone on 10:32. I turned the phone on again at 10:34 but the reminder didn't show on the notification list. I even waited a couple of minutes just to see if it will show but it didn't.

**Comment by cketcham** [comment] 2013-04-09 19:53
duplicate of #34

**Closed as completed by cketcham** 2013-04-09 19:53 UTC
